version: '2.4'

services:
  jdlvgj:
    image: jdlvgj
    environment:
      ENV: development
    build:
      context: .
      dockerfile: DockerfileWeb.Dockerfile
    container_name: jdlvgj
    command: ./jdlgj
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 330s
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      ENV: development
      PORT: 8000
      PG_USER: postgres
      PG_PASSWORD: secret
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DATABSE: jdlgj
    ports:
      - 8000:8000
  postgres:
    image: postgres:11.4
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: jdlgj
    ports:
      - 5432:5432
